In [2]:
# display full output
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = 'all' 

In [4]:
import torch
import torch.nn as nn

# torch.nn.Linear

In [7]:
inputs = torch.randn(10,4) # size (10,4) in neural networks mean there're 10 learning examples in the inputs, each with 4 features
fc = nn.Linear(in_features= 4, out_features = 1) # in_features should be equal to inputs.shape[1], the out_features is the number of features of the target
outputs = fc(inputs) # hence, the outputs would in the size of (10,1)

In [8]:
inputs
outputs

outputs.shape

tensor([[ 0.3102,  0.1271, -0.0823,  1.0858],
        [-1.1686,  1.6650,  1.3797, -0.9915],
        [ 0.3897,  0.3723,  1.0115,  0.1784],
        [ 1.9373, -1.0086,  0.7447,  0.2432],
        [ 0.4305,  0.0627,  0.7668, -1.9446],
        [ 1.0522, -0.2573,  0.6940,  0.0913],
        [-0.0278, -0.0746, -0.0560, -1.1732],
        [-1.1034,  0.8108, -1.1170, -0.2516],
        [-1.1515,  1.2772, -1.6101, -0.8164],
        [-0.6352,  0.9345,  0.4916,  1.1171]])

tensor([[-0.2397],
        [-0.9325],
        [-0.7593],
        [-0.8897],
        [-1.2447],
        [-0.7963],
        [-0.7541],
        [-0.1225],
        [-0.1838],
        [-0.2319]], grad_fn=<AddmmBackward>)

torch.Size([10, 1])

In [9]:
# check the weights and biases in this 'fc' linear layer
fc.weight
fc.bias

Parameter containing:
tensor([[-0.2009, -0.0747, -0.2266,  0.2618]], requires_grad=True)

Parameter containing:
tensor([-0.4708], requires_grad=True)

The algorithm behind the linear layer is actually some basic matrix calculus:
$$outputs = inputs \times weight_T + bias$$
Let's manually implement it

In [12]:
torch.mm(inputs,fc.weight.T).add(fc.bias) # Here we get the same outputs 

tensor([[-0.2397],
        [-0.9325],
        [-0.7593],
        [-0.8897],
        [-1.2447],
        [-0.7963],
        [-0.7541],
        [-0.1225],
        [-0.1838],
        [-0.2319]], grad_fn=<AddBackward0>)

In [17]:
fc1 = nn.Linear(in_features=4, out_features=1, bias=False) # We could remove the bias by setting it to False
fc1(inputs)
torch.mm(inputs,fc1.weight.T) # Again we get the same outputs as fc1(inputs)

tensor([[-0.4864],
        [ 1.7685],
        [ 0.5358],
        [-0.1849],
        [ 1.2545],
        [ 0.1672],
        [ 0.4731],
        [-0.0845],
        [ 0.1134],
        [ 0.1043]], grad_fn=<MmBackward>)

tensor([[-0.4864],
        [ 1.7685],
        [ 0.5358],
        [-0.1849],
        [ 1.2545],
        [ 0.1672],
        [ 0.4731],
        [-0.0845],
        [ 0.1134],
        [ 0.1043]], grad_fn=<MmBackward>)